services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - auth_passport:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  auth_passport:
